### ISSUE TITLE
Where can I get the network code?

### ISSUE THREAD

**Issue by chenyr0021** [joaanna/something_else#1]
I want to run this program on my local server, but it seems that the network in paper has not been uploaded yet.

**Comment by x2ss** [comment]
Same question. Hope have chance to run this wonderful network.

**Comment by ddshan** [comment]
Looking forward to your interaction network code!

**Comment by apple2373** [comment]
I'm also interesting in running the model on the dataset.

**Comment by ruiyan1995** [comment]
Looking forward to your code!

**Comment by joaanna** [comment]
The code can now be found in the `code` folder.
