### ISSUE TITLE
About the Detector

### ISSUE THREAD

**Issue by Mihuadong** [joaanna/something_else#10]
Thanks for your excellent work. I have strong interest in your work. However, it is very difficult for me to train Detector due to limited computing resources. Could you provide the code and pre-trained model of the detector? Thank you very much!

**Comment by ruiyan1995** [comment]
@joaanna Could you provide the detection results?

**Comment by TaeSoo-Kim** [comment]
@joaanna  I would be interested in either the pretrained detector weights or the detections themselves.

Thanks

**Comment by joaanna** [comment]
Hi, I updated the google drive with detected and tracked bounding boxes for both splits. The json files are split into parts, you can concatenate them to get full list.
