### ISSUE TITLE
Missing labels?

### ISSUE THREAD

**Issue by makarandtapaswi** [joaanna/something_else#2]
Hi,

Thanks a lot for the tremendous labeling effort. After downloading the JSONs, I am able to process most videos perfectly well. However, I noticed that (at least one) video, id 15606 (in JSON part 1), has 33 frames, and only 25 of those have box labels. Specifically, labels for frames 22 to 29 are missing. Do you know how/why this may have happened, and whether this is expected/intended?

Thanks!

**Comment by joaanna** [comment]
Hi, 
Have you checked if there actually are objects in those frames? It is possible that the objects disappear, thus there are no annotations for those frames (an example would be 'Taking smth out of smth' and towards the end of the video the objects and hands are not in the scene)

**Comment by makarandtapaswi** [comment]
Sorry, you are right. This was a weird example where the hand and object goes out of frame, but the object re-appears at the edges towards the end of the video because of camera motion.
