### ISSUE TITLE
About object categories

### ISSUE THREAD

**Issue by kennymckormick** [joaanna/something_else#3]
Hi, Joaanna, I got some questions about the released dataset. In your paper, it said that you built the compositional action recognition dataset such that objects in those videos are all frequent (appearing in more than 100 videos). However. I found that there were over 6000 unique placeholders in your released data. I notice there are lots of duplications in those placeholders ('rubix cube', 'rubic cube', etc.). Would you please share the mapping from those placeholders to 'frequent' objects? If so, it will make the taxonomy of objects much clear. Thx a lot!

**Comment by joaanna** [comment]
Hi, you can now find the objects A and B list under `master/code/dataset_splits/compositional`

**Comment by kennymckormick** [comment]
many thx

**Comment by kennymckormick** [comment]
@joaanna Hi, Joaanna. I need to reopen this issue. I need to know how those placeholders are mapped to your new object categories [371 classes]. Seems that is not provided in the released json file.
