### ISSUE TITLE
what's the difference between 'category' and 'standard_category' in annotations

### ISSUE THREAD

**Issue by xxxzhi** [joaanna/something_else#7]
Hi, 

I find there are two categories in the annotations "category" and "standard_category". The standard_category only contains three classes. In your paper, you said a general object embedding for all kinds of objects helps the model to generalize across different combinations. 
Did you experiment on category? I means use the categories of all kinds of objects (over 1000 classes).

**Comment by xxxzhi** [comment]
I get it.

**Comment by iranroman** [comment]
I don't get it, can you please explain? Thanks

**Comment by iranroman** [comment]
I see `'0000'`, `'hand'`, `'0001'`, `'0002'`, `'0003'`. What do these numbers mean? (I guess "hand" is self-explanatory)

**Comment by iranroman** [comment]
I get it

**Comment by ksb-hub** [comment]
I don't get it, can you please explain? Thanks ++
